// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mj3smile/flight-aggregator/internal/provider (interfaces: Provider)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_provider.go -package=mocks github.com/mj3smile/flight-aggregator/internal/provider Provider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/mj3smile/flight-aggregator/internal/domain"
	provider "github.com/mj3smile/flight-aggregator/internal/provider"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockProviderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockProvider)(nil).Name))
}

// RateLimit mocks base method.
func (m *MockProvider) RateLimit() *provider.RateLimitConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RateLimit")
	ret0, _ := ret[0].(*provider.RateLimitConfig)
	return ret0
}

// RateLimit indicates an expected call of RateLimit.
func (mr *MockProviderMockRecorder) RateLimit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RateLimit", reflect.TypeOf((*MockProvider)(nil).RateLimit))
}

// Search mocks base method.
func (m *MockProvider) Search(ctx context.Context, req domain.SearchRequest) ([]domain.Flight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, req)
	ret0, _ := ret[0].([]domain.Flight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockProviderMockRecorder) Search(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockProvider)(nil).Search), ctx, req)
}
